// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTuIHoGnc7ERzJOGkbtIRfQ5Upg0Hw-CU',
    appId: '1:20346872818:web:6bf1ccf35a7a8416cb816b',
    messagingSenderId: '20346872818',
    projectId: 'dreamdose-a900a',
    authDomain: 'dreamdose-a900a.firebaseapp.com',
    databaseURL: 'https://dreamdose-a900a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dreamdose-a900a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7TWztT0NQvwf76SRKQE218uARGse5O6o',
    appId: '1:20346872818:android:91624e5446037ba3cb816b',
    messagingSenderId: '20346872818',
    projectId: 'dreamdose-a900a',
    databaseURL: 'https://dreamdose-a900a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dreamdose-a900a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMgqvJwvmixIXYQr5vmSyi8L3Cdvu0zZc',
    appId: '1:20346872818:ios:8815332874dbe382cb816b',
    messagingSenderId: '20346872818',
    projectId: 'dreamdose-a900a',
    databaseURL: 'https://dreamdose-a900a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dreamdose-a900a.appspot.com',
    iosBundleId: 'com.example.dreamDose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMgqvJwvmixIXYQr5vmSyi8L3Cdvu0zZc',
    appId: '1:20346872818:ios:befb6bac6d011d8acb816b',
    messagingSenderId: '20346872818',
    projectId: 'dreamdose-a900a',
    databaseURL: 'https://dreamdose-a900a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dreamdose-a900a.appspot.com',
    iosBundleId: 'com.example.dreamDose.RunnerTests',
  );
}
